services:
  superbot:
    build: .
    restart: on-failure:3
    environment:
      - DEBUG=false
    volumes:
      - ./conf/ubuntu/dev/SuperBot.json:/app/conf.json:ro
      - ./ubuntu:/app/ubuntu
    networks:
      - bot-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          memory: 128M
  easybot:
    build: .
    restart: on-failure:3
    environment:
      - DEBUG=false
    volumes:
      - ./conf/ubuntu/dev/EasyBot.json:/app/conf.json:ro
      - ./ubuntu:/app/ubuntu
    networks:
      - bot-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          memory: 128M
  arenabot:
    build: .
    restart: on-failure:3
    environment:
      - DEBUG=false
    volumes:
      - ./conf/ubuntu/dev/ArenaBot.json:/app/conf.json:ro
      - ./ubuntu:/app/ubuntu
    networks:
      - bot-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          memory: 128M

networks:
  bot-network:
    driver: bridge
